apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: chat-server:latest
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "5000"
        - name: POSTGRES_HOST
          value: postgres
        - name: MONGO_URI
          value: mongodb://admin:mongopassword@mongo:27017/chat_db?authSource=admin
        - name: REDIS_URL
          value: redis://redis:6379
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
